name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: composer validate
      run: composer validate

    - name: composer check-platform-reqs
      run: composer check-platform-reqs

    - name: composer install
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHPCS
      run: composer phpcs

    - name: PHPStan
      run: composer phpstan

    - name: PHPUnit
      run: composer test
